services:
  - type: web
    name: student-placement-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:app" --timeout 120 --workers 2
    plan: free
    autoDeploy: true
    disk:
      name: model
      mountPath: /app/model
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health