services:
  - type: web
    name: student-placement-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/models
      sizeGB: 1